In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import numpy as np

In [2]:
movie_df=pd.read_csv("movie dataset.csv")

In [3]:
movie_df

,Movie Title,Ratinng,genre,act,Plot
0,3 Idiots,8.4,"Comedy, Drama","Aamir Khan, Madhavan, Mona Singh, Sharman Josh...","papadum, hairy chest, against the system, comi..."
1,Taare Zameen Par,8.3,"Drama, Family","Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...","teacher student relationship, dyslexia, agains..."
2,PK,8.1,"Comedy, Drama, Sci-Fi","Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...","guru, religion, tv reporter, alien on earth, p..."
3,Dangal,8.3,"Action, Biography, Drama","Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...","small town, father daughter relationship, male..."
4,Rang De Basanti,8.1,"Comedy, Crime, Drama","Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...","delhi india, murder, friend, india, awakening,..."
...,...,...,...,...,...
806,Parde Ke Peechey,5.9,Action,"Vinod Mehra, Yogeeta Bali, Pran Sikand, Bindu ...",crook
807,Dhamkee,4.0,"Action, Comedy","Ravi Teja, Anushka Shetty, Krishna, Pradeep Si...",sorry
808,Chhoo Mantar,6.0,Comedy,"Shyama, Johnny Walker, Anita Guha, Gajanan Jag...","rescue, beating, river, village, wedding, flir..."
809,Ladki Sahyadri Ki,5.0,"Musical, Drama","Shalini Abhyankar, Keshavrao Date, Vatsala Des...",sorry


In [4]:
movie_df.isnull().sum()

Movie Title    0
Ratinng        0
genre          0
act            0
Plot           0
dtype: int64

In [5]:
movie_df.dtypes

Movie Title     object
Ratinng        float64
genre           object
act             object
Plot            object
dtype: object

In [6]:
vextor=TfidfVectorizer()

In [7]:
transformdata=vextor.fit_transform(movie_df['genre'])
transformdata[1]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (1, 22)>

In [8]:
transformdata[1].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.32374257, 0.9461452 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [9]:
transformdata[2].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.23854688,
        0.        , 0.        , 0.15553797, 0.        , 0.        ,
        0.67782864, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.67782864, 0.        , 0.        ,
        0.        , 0.        ]])

In [10]:
indexed=pd.Series(data=movie_df.index,index=movie_df['Movie Title'])

In [11]:
indexed

Movie Title
3 Idiots               0
Taare Zameen Par       1
PK                     2
Dangal                 3
Rang De Basanti        4
                    ... 
Parde Ke Peechey     806
Dhamkee              807
Chhoo Mantar         808
Ladki Sahyadri Ki    809
Madadgaar            810
Length: 811, dtype: int64

In [27]:
dis=linear_kernel(transformdata[0],transformdata)

In [25]:
dis

array([[1.]])

In [30]:
score=pd.DataFrame(dis).T
score

,0
0,1.000000
1,0.176821
2,0.284775
3,0.145397
4,0.687132
...,...
806,0.000000
807,0.590766
808,0.837669
809,0.189866


In [15]:
score.columns=["score"]

In [16]:
score.sort_values("score",ascending=False)

,score
8,1.0
0,1.0
51,1.0
358,1.0
755,1.0
...,...
765,0.0
767,0.0
766,0.0
773,0.0


In [17]:
 movie_df.head(10)

,Movie Title,Ratinng,genre,act,Plot
0,3 Idiots,8.4,"Comedy, Drama","Aamir Khan, Madhavan, Mona Singh, Sharman Josh...","papadum, hairy chest, against the system, comi..."
1,Taare Zameen Par,8.3,"Drama, Family","Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...","teacher student relationship, dyslexia, agains..."
2,PK,8.1,"Comedy, Drama, Sci-Fi","Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...","guru, religion, tv reporter, alien on earth, p..."
3,Dangal,8.3,"Action, Biography, Drama","Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...","small town, father daughter relationship, male..."
4,Rang De Basanti,8.1,"Comedy, Crime, Drama","Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...","delhi india, murder, friend, india, awakening,..."
5,My Name Is Khan,7.9,"Drama, Romance","Shah Rukh Khan, Kajol, Sheetal Menon, Katie Am...","barack obama character, asperger's syndrome, r..."
6,Gangs of Wasseypur,8.2,"Action, Comedy, Crime","Manoj Bajpayee, Richa Chadha, Nawazuddin Siddi...","revenge, blood, gun, abuse, gangster, violence..."
7,Chak De! India,8.1,"Drama, Family, Sport","Shah Rukh Khan, Vidya Malvade, Sagarika Ghatge...","team, hockey, coach, brawl, boyfriend girlfrie..."
8,Munna Bhai M.B.B.S.,8.1,"Comedy, Drama","Sanjay Dutt, Arshad Warsi, Gracy Singh, Boman ...","assumed identity, hazing, love, deception, abd..."
9,Bajrangi Bhaijaan,8.1,"Action, Adventure, Comedy","Salman Khan, Harshaali Malhotra, Nawazuddin Si...","muscleman, machismo, tough guy, torture, inter..."


In [18]:
movie_df.iloc[8,0]

'Munna Bhai M.B.B.S.'

In [31]:
indexed["My Name Is Khan"]

np.int64(5)

In [32]:
def movie_recom(name,n): 
    dis=linear_kernel(transformdata[indexed[name]],transformdata)
    score=pd.DataFrame(dis).T
    score.columns=["score"]
    score.sort_values("score",ascending=False)
    lst=[]
    for i in range(0,n+1):
        Movie_title={"Movie_title":movie_df['Movie Title'][score.index[i]],
                     "Ratinng":movie_df['Ratinng'][score.index[i]],
                     "genre":movie_df['genre'][score.index[i]],
                     "act":movie_df['act'][score.index[i]]
                    }
        lst.append(Movie_title)
    return lst
    

In [34]:
movie_recom("3 Idiots",10)

[{'Movie_title': '3 Idiots',
  'Ratinng': np.float64(8.4),
  'genre': 'Comedy, Drama',
  'act': 'Aamir Khan, Madhavan, Mona Singh, Sharman Joshi, Kareena Kapoor, Boman Irani, Omi Vaidya, Olivier Lafont, Rahul Kumar, Parikshit Sahni, Farida Dadi, Amardeep Jha, Mukund Bhatt, Chaitali Bose, Jaaved Jaaferi, Jayant Kripalani, Arun Bali, Shoaib Ahmed'},
 {'Movie_title': 'Taare Zameen Par',
  'Ratinng': np.float64(8.3),
  'genre': 'Drama, Family',
  'act': 'Darsheel Safary, Aamir Khan, Tisca Chopra, Vipin Sharma, Sachet Engineer, Tanay Chheda, Lalitha Lajmi, Girija Oak, Ravi Khanvilkar, Pratima Kulkarni, Meghna Malik, Sonali Sachdev, Sanjay Dadhich, Rajgopal Iyer, Bugs Bhargava Krishna, Shankar Sachdev, M.K. Raina, Gurkirtan'},
 {'Movie_title': 'PK',
  'Ratinng': np.float64(8.1),
  'genre': 'Comedy, Drama, Sci-Fi',
  'act': "Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman Irani, Rajinder Sharma Nanu, Sushant Singh Rajput, Sai Gundewar, Ram Sethi, Ignace De Groote, Donder In t' Hooi, Plabita Bo

In [22]:
df=pd.DataFrame(movie_recom("3 Idiots",5))

In [23]:
df

,Movie_title,Ratinng,genre,act
0,3 Idiots,8.4,"Comedy, Drama","Aamir Khan, Madhavan, Mona Singh, Sharman Josh..."
1,Taare Zameen Par,8.3,"Drama, Family","Darsheel Safary, Aamir Khan, Tisca Chopra, Vip..."
2,PK,8.1,"Comedy, Drama, Sci-Fi","Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman..."
3,Dangal,8.3,"Action, Biography, Drama","Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,..."
4,Rang De Basanti,8.1,"Comedy, Crime, Drama","Aamir Khan, Soha Ali Khan, Siddharth, Sharman ..."
5,My Name Is Khan,7.9,"Drama, Romance","Shah Rukh Khan, Kajol, Sheetal Menon, Katie Am..."
